// <auto-generated />
using System;
using DataBaseLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseLayer.Migrations
{
    [DbContext(typeof(VendingAppContext))]
    [Migration("20240610213500_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataBaseLayer.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Fanta"
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Pepsi"
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "Coca-Cola"
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Schweppes"
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "Sprite"
                        });
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 20,
                            ImageUrl = "/img/1.jpg",
                            ItemType = 0,
                            Price = 1m,
                            Title = "1 рубль"
                        },
                        new
                        {
                            Id = 2,
                            Count = 20,
                            ImageUrl = "/img/2.jpg",
                            ItemType = 0,
                            Price = 2m,
                            Title = "2 рубля"
                        },
                        new
                        {
                            Id = 3,
                            Count = 20,
                            ImageUrl = "/img/5.jpg",
                            ItemType = 0,
                            Price = 5m,
                            Title = "5 рублей"
                        },
                        new
                        {
                            Id = 4,
                            Count = 20,
                            ImageUrl = "/img/10.jpg",
                            ItemType = 0,
                            Price = 10m,
                            Title = "10 рублей"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            Count = 20,
                            ImageUrl = "/img/coca-cola03.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Coca-Cola 0.33"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            Count = 20,
                            ImageUrl = "/img/coca-cola05.jpg",
                            ItemType = 1,
                            Price = 25m,
                            Title = "Coca-Cola 0.5"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 3,
                            Count = 20,
                            ImageUrl = "/img/coca-cola10.jpg",
                            ItemType = 1,
                            Price = 35m,
                            Title = "Coca-Cola 1.0"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            Count = 20,
                            ImageUrl = "/img/coca-colaLimon03.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Coca-Cola Лимон 0.33"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Count = 20,
                            ImageUrl = "/img/coca-colaLimon05.jpg",
                            ItemType = 1,
                            Price = 25m,
                            Title = "Coca-Cola Лимон 0.5"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            Count = 20,
                            ImageUrl = "/img/coca-colaLimon10.jpg",
                            ItemType = 1,
                            Price = 35m,
                            Title = "Coca-Cola Лимон 1.0"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            Count = 20,
                            ImageUrl = "/img/fantaApelsin03.jpg",
                            ItemType = 1,
                            Price = 21m,
                            Title = "Fanta Апельсин 0.33"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 1,
                            Count = 20,
                            ImageUrl = "/img/fantaApelsin05.jpg",
                            ItemType = 1,
                            Price = 26m,
                            Title = "Fanta Апельсин 0.5"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            Count = 20,
                            ImageUrl = "/img/fantaApelsin10.jpg",
                            ItemType = 1,
                            Price = 34m,
                            Title = "Fanta Апельсин 1.0"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            Count = 20,
                            ImageUrl = "/img/fantaVinograd03.jpg",
                            ItemType = 1,
                            Price = 22m,
                            Title = "Fanta Виноград 0.33"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 1,
                            Count = 20,
                            ImageUrl = "/img/fantaVinograd05.jpg",
                            ItemType = 1,
                            Price = 26m,
                            Title = "Fanta Виноград 0.5"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 1,
                            Count = 20,
                            ImageUrl = "/img/fantaVinograd10.jpg",
                            ItemType = 1,
                            Price = 36m,
                            Title = "Fanta Виноград 1.0"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 2,
                            Count = 20,
                            ImageUrl = "/img/pepsi03.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Pepsi 0.33"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 2,
                            Count = 25,
                            ImageUrl = "/img/pepsi05.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Pepsi 0.5"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 2,
                            Count = 35,
                            ImageUrl = "/img/pepsi10.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Pepsi 1.0"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 2,
                            Count = 24,
                            ImageUrl = "/img/pepsiZero03.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Pepsi Zero 0.33"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 2,
                            Count = 29,
                            ImageUrl = "/img/pepsiZero05.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Pepsi Zero 0.5"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 2,
                            Count = 48,
                            ImageUrl = "/img/pepsiZero10.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Pepsi Zero 1.0"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 4,
                            Count = 22,
                            ImageUrl = "/img/schweppesKlukva03.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Schweppes Клюква 0.33"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 4,
                            Count = 26,
                            ImageUrl = "/img/schweppesKlukva05.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Schweppes Клюква 0.5"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 4,
                            Count = 38,
                            ImageUrl = "/img/schweppesKlukva10.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Schweppes Клюква 1.0"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 4,
                            Count = 22,
                            ImageUrl = "/img/schweppesLimon03.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Schweppes Лимон 0.33"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 4,
                            Count = 27,
                            ImageUrl = "/img/schweppesLimon05.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Schweppes Лимон 0.5"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 4,
                            Count = 39,
                            ImageUrl = "/img/schweppesLimon10.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Schweppes Лимон 1.0"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 5,
                            Count = 20,
                            ImageUrl = "/img/sprite03.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Sprite 0.33"
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 5,
                            Count = 28,
                            ImageUrl = "/img/sprite05.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Sprite 0.5"
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 5,
                            Count = 38,
                            ImageUrl = "/img/sprite10.jpg",
                            ItemType = 1,
                            Price = 20m,
                            Title = "Sprite 1.0"
                        });
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActType = 1,
                            DateTime = new DateTime(2024, 6, 8, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ActType = 1,
                            DateTime = new DateTime(2024, 6, 9, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataBaseLayer.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemChange")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemChange = 10,
                            ItemCount = 10,
                            ItemId = 1,
                            ItemPrice = 1m,
                            ItemType = 0,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            ItemChange = 1,
                            ItemCount = 1,
                            ItemId = 4,
                            ItemPrice = 10m,
                            ItemType = 0,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemChange = -1,
                            ItemCount = 1,
                            ItemId = 5,
                            ItemPrice = 20m,
                            ItemType = 1,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 4,
                            ItemChange = 10,
                            ItemCount = 10,
                            ItemId = 1,
                            ItemPrice = 1m,
                            ItemType = 0,
                            OrderId = 2
                        },
                        new
                        {
                            Id = 5,
                            ItemChange = 3,
                            ItemCount = 3,
                            ItemId = 4,
                            ItemPrice = 10m,
                            ItemType = 0,
                            OrderId = 2
                        },
                        new
                        {
                            Id = 6,
                            ItemChange = -2,
                            ItemCount = 2,
                            ItemId = 5,
                            ItemPrice = 20m,
                            ItemType = 1,
                            OrderId = 2
                        });
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Item", b =>
                {
                    b.HasOne("DataBaseLayer.Entities.Brand", "Brand")
                        .WithMany("ProductsItems")
                        .HasForeignKey("BrandId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("DataBaseLayer.Entities.OrderDetail", b =>
                {
                    b.HasOne("DataBaseLayer.Entities.Order", "Order")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Brand", b =>
                {
                    b.Navigation("ProductsItems");
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Order", b =>
                {
                    b.Navigation("OrdersDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
