// <auto-generated />
using System;
using DataBaseLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseLayer.Migrations
{
    [DbContext(typeof(VendingAppContext))]
    [Migration("20240610101521_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataBaseLayer.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Fanta"
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Pepsi"
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "Cola"
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Merinda 0.33"
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "Sprite 0.5"
                        },
                        new
                        {
                            Id = 6,
                            BrandName = "Shweps 0.5"
                        });
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 20,
                            ItemType = 0,
                            Price = 1m,
                            Title = "1 рубль"
                        },
                        new
                        {
                            Id = 2,
                            Count = 20,
                            ItemType = 0,
                            Price = 2m,
                            Title = "2 рубля"
                        },
                        new
                        {
                            Id = 3,
                            Count = 20,
                            ItemType = 0,
                            Price = 5m,
                            Title = "5 рублей"
                        },
                        new
                        {
                            Id = 4,
                            Count = 20,
                            ItemType = 0,
                            Price = 10m,
                            Title = "10 рублей"
                        },
                        new
                        {
                            Id = 5,
                            Count = 20,
                            ItemType = 1,
                            Price = 20m,
                            Title = "Fanta 0.33"
                        },
                        new
                        {
                            Id = 6,
                            Count = 20,
                            ItemType = 1,
                            Price = 25m,
                            Title = "Fanta 0.5"
                        },
                        new
                        {
                            Id = 7,
                            Count = 20,
                            ItemType = 1,
                            Price = 22m,
                            Title = "Pepsi 0.33"
                        },
                        new
                        {
                            Id = 8,
                            Count = 20,
                            ItemType = 1,
                            Price = 27m,
                            Title = "Pepsi 0.35"
                        },
                        new
                        {
                            Id = 9,
                            Count = 20,
                            ItemType = 1,
                            Price = 25m,
                            Title = "Cola 0.33"
                        },
                        new
                        {
                            Id = 10,
                            Count = 20,
                            ItemType = 1,
                            Price = 30m,
                            Title = "Cola 0.5"
                        },
                        new
                        {
                            Id = 11,
                            Count = 20,
                            ItemType = 1,
                            Price = 25m,
                            Title = "Merinda 0.33"
                        },
                        new
                        {
                            Id = 12,
                            Count = 20,
                            ItemType = 1,
                            Price = 25m,
                            Title = "Merinda 0.5"
                        });
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActType = 1,
                            DateTime = new DateTime(2024, 6, 8, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ActType = 1,
                            DateTime = new DateTime(2024, 6, 9, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataBaseLayer.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemChange")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemChange = 10,
                            ItemCount = 10,
                            ItemId = 1,
                            ItemPrice = 1m,
                            ItemType = 0,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            ItemChange = 1,
                            ItemCount = 1,
                            ItemId = 4,
                            ItemPrice = 10m,
                            ItemType = 0,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemChange = -1,
                            ItemCount = 1,
                            ItemId = 5,
                            ItemPrice = 20m,
                            ItemType = 1,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 4,
                            ItemChange = 10,
                            ItemCount = 10,
                            ItemId = 1,
                            ItemPrice = 1m,
                            ItemType = 0,
                            OrderId = 2
                        },
                        new
                        {
                            Id = 5,
                            ItemChange = 3,
                            ItemCount = 3,
                            ItemId = 4,
                            ItemPrice = 10m,
                            ItemType = 0,
                            OrderId = 2
                        },
                        new
                        {
                            Id = 6,
                            ItemChange = -2,
                            ItemCount = 2,
                            ItemId = 5,
                            ItemPrice = 20m,
                            ItemType = 1,
                            OrderId = 2
                        });
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Item", b =>
                {
                    b.HasOne("DataBaseLayer.Entities.Brand", "Brand")
                        .WithMany("ProductsItems")
                        .HasForeignKey("BrandId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("DataBaseLayer.Entities.OrderDetail", b =>
                {
                    b.HasOne("DataBaseLayer.Entities.Order", "Order")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Brand", b =>
                {
                    b.Navigation("ProductsItems");
                });

            modelBuilder.Entity("DataBaseLayer.Entities.Order", b =>
                {
                    b.Navigation("OrdersDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
